<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="3" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Setting up report and Test getting ready]]>
    </line>
    <line>
      <![CDATA[Setting Done-Test can be Stated]]>
    </line>
    <line>
      <![CDATA[Trying to start browser and getting application ready]]>
    </line>
    <line>
      <![CDATA[Browser and application is up and running]]>
    </line>
    <line>
      <![CDATA[Test is about to end]]>
    </line>
    <line>
      <![CDATA[Test completed>>Report generated]]>
    </line>
    <line>
      <![CDATA[Test is about to end]]>
    </line>
    <line>
      <![CDATA[Test completed>>Report generated]]>
    </line>
    <line>
      <![CDATA[Test is about to end]]>
    </line>
    <line>
      <![CDATA[Test completed>>Report generated]]>
    </line>
    <line>
      <![CDATA[Test is about to end]]>
    </line>
    <line>
      <![CDATA[Test completed>>Report generated]]>
    </line>
  </reporter-output>
  <suite started-at="2020-09-13T11:44:36Z" name="Suite" finished-at="2020-09-13T11:45:08Z" duration-ms="32072">
    <groups>
    </groups>
    <test started-at="2020-09-13T11:44:36Z" name="Test" finished-at="2020-09-13T11:45:08Z" duration-ms="32072">
      <class name="com.automation.testcases.LoginTest">
        <test-method is-config="true" signature="setupSuite()[pri:0, instance:com.automation.testcases.LoginTest@534a5a98]" started-at="2020-09-13T17:14:35Z" name="setupSuite" finished-at="2020-09-13T17:14:36Z" duration-ms="500" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Setting up report and Test getting ready]]>
            </line>
            <line>
              <![CDATA[Setting Done-Test can be Stated]]>
            </line>
          </reporter-output>
        </test-method> <!-- setupSuite -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.automation.testcases.LoginTest@534a5a98]" started-at="2020-09-13T17:14:36Z" name="setup" finished-at="2020-09-13T17:14:44Z" duration-ms="7896" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Trying to start browser and getting application ready]]>
            </line>
            <line>
              <![CDATA[Browser and application is up and running]]>
            </line>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="LoginApp(java.lang.String, java.lang.String)[pri:0, instance:com.automation.testcases.LoginTest@534a5a98]" started-at="2020-09-13T17:14:44Z" name="LoginApp" data-provider="wordpressData" finished-at="2020-09-13T17:14:49Z" duration-ms="4958" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to Login expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to Login expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.automation.testcases.LoginTest.LoginApp(LoginTest.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginApp -->
        <test-method is-config="true" signature="tearDownMethod(org.testng.ITestResult)[pri:0, instance:com.automation.testcases.LoginTest@534a5a98]" started-at="2020-09-13T17:14:49Z" name="tearDownMethod" finished-at="2020-09-13T17:14:49Z" duration-ms="609" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginApp status=FAILURE method=LoginTest.LoginApp(java.lang.String, java.lang.String)[pri:0, instance:com.automation.testcases.LoginTest@534a5a98] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test is about to end]]>
            </line>
            <line>
              <![CDATA[Test completed>>Report generated]]>
            </line>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
        <test-method signature="LoginApp(java.lang.String, java.lang.String)[pri:0, instance:com.automation.testcases.LoginTest@534a5a98]" started-at="2020-09-13T17:14:49Z" name="LoginApp" data-provider="wordpressData" finished-at="2020-09-13T17:14:54Z" duration-ms="4847" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo12]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to Login expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to Login expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.automation.testcases.LoginTest.LoginApp(LoginTest.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginApp -->
        <test-method is-config="true" signature="tearDownMethod(org.testng.ITestResult)[pri:0, instance:com.automation.testcases.LoginTest@534a5a98]" started-at="2020-09-13T17:14:54Z" name="tearDownMethod" finished-at="2020-09-13T17:14:55Z" duration-ms="391" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginApp status=FAILURE method=LoginTest.LoginApp(java.lang.String, java.lang.String)[pri:0, instance:com.automation.testcases.LoginTest@534a5a98] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test is about to end]]>
            </line>
            <line>
              <![CDATA[Test completed>>Report generated]]>
            </line>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
        <test-method signature="LoginApp(java.lang.String, java.lang.String)[pri:0, instance:com.automation.testcases.LoginTest@534a5a98]" started-at="2020-09-13T17:14:55Z" name="LoginApp" data-provider="wordpressData" finished-at="2020-09-13T17:15:00Z" duration-ms="5209" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to Login expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to Login expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.automation.testcases.LoginTest.LoginApp(LoginTest.java:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginApp -->
        <test-method is-config="true" signature="tearDownMethod(org.testng.ITestResult)[pri:0, instance:com.automation.testcases.LoginTest@534a5a98]" started-at="2020-09-13T17:15:00Z" name="tearDownMethod" finished-at="2020-09-13T17:15:00Z" duration-ms="367" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginApp status=FAILURE method=LoginTest.LoginApp(java.lang.String, java.lang.String)[pri:0, instance:com.automation.testcases.LoginTest@534a5a98] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test is about to end]]>
            </line>
            <line>
              <![CDATA[Test completed>>Report generated]]>
            </line>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
        <test-method signature="LoginApp(java.lang.String, java.lang.String)[pri:0, instance:com.automation.testcases.LoginTest@534a5a98]" started-at="2020-09-13T17:15:00Z" name="LoginApp" data-provider="wordpressData" finished-at="2020-09-13T17:15:07Z" duration-ms="6684" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[demo123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginApp -->
        <test-method is-config="true" signature="tearDownMethod(org.testng.ITestResult)[pri:0, instance:com.automation.testcases.LoginTest@534a5a98]" started-at="2020-09-13T17:15:07Z" name="tearDownMethod" finished-at="2020-09-13T17:15:07Z" duration-ms="407" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginApp status=SUCCESS method=LoginTest.LoginApp(java.lang.String, java.lang.String)[pri:0, instance:com.automation.testcases.LoginTest@534a5a98] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test is about to end]]>
            </line>
            <line>
              <![CDATA[Test completed>>Report generated]]>
            </line>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.automation.testcases.LoginTest@534a5a98]" started-at="2020-09-13T17:15:07Z" name="teardown" finished-at="2020-09-13T17:15:08Z" duration-ms="632" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.automation.testcases.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
